sudo: required

language: python

cache:
  pip: true

python:
  - "3.5"
  - "3.6"
  - "3.7"

addons:
  apt:
    packages:
      - mpich
      - libmpich-dev

before_install:
  - pip install -r requirements.txt

install:
  - python setup.py build_ext --inplace

script:
  - pytest -v
