sudo: required
dist: trusty

language: python

python:
    2.7
    3.5
    3.6
    3.7

addons:
    apt:
        packages:
            - libmpich-dev
            - mpich

before_install:
    - pip install pandas matplotlib scipy numpy h5py mpi4py pyblock pyscf
    - cd
    # testcode
    - git clone git://github.com/jsspencer/testcode

install:
    - cd -
    - python setup.py install

script:
    - cd tests
    - export PYTHONPATH=$PYTHONPATH:$HOME/pauxy
    - python -c "import sys; print (sys.path)"
    - python -c "import pauxy; import pauxy.analysis"
    - python -c "import pauxy.qmc"
    - $HOME/testcode/bin/testcode.py -vvv
    - cd $HOME/pauxy
    - python -u -W ignore::DeprecationWarning -m unittest discover -v

after_failure:
    - cat */*.err*
