sudo: required

language: python

cache:
  pip: true

python:
  - "3.5"
  - "3.6"
  - "3.7"

addons:
  apt:
    packages:
      - mpich
      - libmpich-dev

before_install:
  - pip install -r requirements.txt
  - pip install pyscf
  - git clone https://github.com/pauxy-qmc/pauxy_test_data.git
  - git clone https://github.com/jsspencer/testcode.git

install:
  - python setup.py build_ext --inplace

script:
  - pytest -v
  - ls
  - cd pauxy_test_data
  - python ../bin/testcode.py -vvv  -e ../bin/pauxy run --user-option=pauxy launch_parallel 'mpirun -np tc.nprocs python -u'
