sudo: required
dist: trusty

language: python

python:
    3.6

addons:
    apt:
        packages:
            - libmpich-dev
            - mpich

before_install:
    - pip install pandas matplotlib scipy numpy h5py mpi4py
    # testcode
    - git clone git://github.com/jsspencer/testcode

script:
    - pwd
    - cd tests
    # Only run a short subset of the tests
    - $HOME/testcode/bin/testcode.py
